import React from "react";
import { useGLTF } from "@react-three/drei";

export function MoonHigh(props) {
  const { nodes, materials } = useGLTF("/glb/moon_high.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0001.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0002.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0003.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0004.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0005.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0006.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0007.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0008.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0009.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0010.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0011.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0012.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0013.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0014.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0015.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0016.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0017.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0018.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0019.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0020.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0021.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0022.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0023.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0024.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0025.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0026.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0027.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0028.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0029.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0030.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0031.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0032.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0033.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0034.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0035.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0036.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0037.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0038.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0039.geometry}
              material={materials.MoonSub}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MoonHigh_MoonSub_0040.geometry}
              material={materials.MoonSub}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/glb/moon_high.glb");
